import React,{useState,useEffect} from 'react';
import {motion,AnimatePresence} from 'motion/react';
import {ChevronLeft,Check,ShieldCheck,MessageCircle,LoaderCircle,UserRound,Eye,EyeOff} from 'lucide-react';
import Bot from './Bot';
import {steps} from './logic';
import ShinyText from './ShinyText';
export default function Entry({blocked=false,Logo,user,profile,loading,error,onRetry,onStart,onContinue,onImport,legacy,saveError,onSaveRetry,onAuthenticate,onSignOut,onDashboard}){
 const [view,setView]=useState('welcome'),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[formError,setFormError]=useState('');
 async function start(imported=false){setFormError('');setBusy(true);try{await(imported?onImport():onStart())}catch(e){setFormError(e.message)}finally{setBusy(false)}}
 function changeView(next){setView(next);setFormError('');window.scrollTo({top:0,behavior:'instant'})}
 const [showPassword,setShowPassword]=useState(false);
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[google,setGoogle]=useState(false);useEffect(()=>{fetch('/api/auth/status').then(r=>r.json()).then(d=>setGoogle(d.google)).catch(()=>{});if(new URLSearchParams(location.search).has('auth_error'))setFormError('Não foi possível entrar com Google. Tente novamente ou use e-mail e senha.')},[]);
 async function authenticate(e){e.preventDefault();setBusy(true);setFormError('');try{await onAuthenticate(view,{email,password,accepted})}catch(e){setFormError(e.message)}finally{setBusy(false)}}
 const hasProfile=!!profile;
 const name=profile?.name?.split(' ')[0];
 return <div className="entry-shell" inert={blocked}><header className="entry-header"><Logo/><span>SEU RITMO. SEU REP.</span></header><div className="entry-layout"><div className="entry-brand-scene" aria-hidden="true"><img src="/gym.jpg" alt=""/><div className="entry-scene-shade"/><div className="entry-scene-copy"><span>REP / PERFORMANCE</span><p>A sua próxima<br/>versão começa<br/>com você.</p><div><span>01</span><span>UMA REPETIÇÃO DE CADA VEZ.</span></div></div></div><main className="entry-surface"><AnimatePresence mode="wait"><motion.div className={'entry-content entry-'+view} key={view} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.25}}>
 {view!=='welcome'&&<button className="entry-back" onClick={()=>changeView('welcome')}><ChevronLeft size={18}/>Voltar</button>}
 <div className="entry-companion"><Bot interactive/><span className="auth-companion-note">{view==='welcome'?'':'Seu companheiro REP'}</span></div>
 <div className="entry-eyebrow"><span className="entry-brand-rule"/><span>REP INTELLIGENCE</span></div>
 {view==='welcome'?<><h1>{hasProfile?<>Bom ter você<br/>de volta{name?`, ${name}`:''}.</>:<>Seu treino.<br/><span>Seu ritmo.</span></>}</h1><p className="entry-description">{hasProfile?(profile.complete?'Seu plano, seus treinos e a sua conversa estão aqui. Vamos continuar?':'Seu perfil está em construção. O REP continua de onde você parou.'):'Uma conversa para conhecer você. Um plano para acompanhar seu próximo passo.'}</p><div className="entry-facts"><span><MessageCircle size={15}/>{hasProfile&&!profile.complete?`${steps.length-(profile.step||0)} passos para deixar tudo pronto`:'Uma pergunta por vez'}</span><span><span className="entry-fact-dot"/>No seu ritmo</span></div><div className="entry-actions"><button className="entry-primary" disabled={loading||!!error} onClick={()=>hasProfile?onContinue():changeView('register')}>{loading?<><LoaderCircle className="spin" size={18}/>Preparando seu espaço…</>:hasProfile?(profile.complete?'Continuar com o REP':'Continuar meu perfil'):'Criar meu perfil'}</button><button className="entry-secondary" disabled={loading||!!error} onClick={()=>hasProfile&&profile.complete?onDashboard():changeView('login')}>{hasProfile&&profile.complete?'Abrir meu painel':'Entrar na minha conta'}</button></div></>:<><h1>{view==='login'?<>Seu espaço.<br/>Seu <span>ritmo.</span></>:<>Vamos começar<br/>por <span>você.</span></>}</h1><p className="entry-description">{view==='login'?'Entre para retomar sua conversa, seus treinos e sua evolução.':'Seu perfil começa no chat. Você responde, o REP escuta e conhece seu objetivo.'}</p>
 {user?<><div className="entry-identity"><div className="entry-identity-icon"><UserRound size={22}/></div><div><strong>{user.name||'Sua conta REP'}</strong><span>{user.email}</span></div><ShieldCheck size={18}/></div><button className="entry-switch" onClick={async()=>{try{await onSignOut()}catch{setFormError('Não foi possível sair da conta. Tente novamente.')}}}>Usar outra conta</button>{view==='register'&&!hasProfile&&<><div className="entry-process"><span><i>1</i>Crie seu perfil</span><span><i>2</i>Converse com o REP</span><span><i>3</i>Conheça seu plano</span></div><label className="entry-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Tenho 13 anos ou mais e li e aceito os <a href="/termos" target="_top">Termos de Uso</a> e a <a href="/privacidade" target="_top">Política de Privacidade</a>. Se tenho menos de 18, usarei o REP com acompanhamento de responsável e profissional.</span></label></>}
 <div className="entry-actions">{hasProfile?<button className="entry-primary" onClick={onContinue}>Continuar {profile.complete?'minha conversa':'meu perfil'}</button>:view==='register'?<button className="entry-primary" disabled={!accepted||busy} onClick={()=>start()}>{busy?<><LoaderCircle className="spin" size={18}/>Criando seu espaço…</>:'Criar perfil e conversar'}</button>:<><p className="entry-no-profile">Sua conta está conectada. Falta só criar seu perfil REP.</p><button className="entry-primary" onClick={()=>setView('register')}>Criar meu perfil</button>{legacy&&<button className="entry-secondary" disabled={busy} onClick={()=>start(true)}>{busy?'Recuperando…':`Recuperar perfil de ${legacy.name} deste aparelho`}</button>}</>}
 <button className="entry-switch" onClick={()=>{changeView(view==='register'?'login':'register')}}>{view==='register'?'Já tenho um perfil. Entrar':'Primeira vez no REP? Criar perfil'}</button></div></>:<form className="entry-auth-form" onSubmit={authenticate}><label>E-mail<input required type="email" autoComplete="email" placeholder="voce@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<div className="auth-password"><input required type={showPassword?'text':'password'} minLength={10} maxLength={128} autoComplete={view==='register'?'new-password':'current-password'} placeholder="Pelo menos 10 caracteres" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></label>{view==='register'&&<label className="entry-consent"><input required type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Tenho 13 anos ou mais e li e aceito os <a href="/termos" target="_top">Termos de Uso</a> e a <a href="/privacidade" target="_top">Política de Privacidade</a>. Se tenho menos de 18, usarei o REP com acompanhamento de responsável e profissional.</span></label>}<button className="entry-primary" disabled={busy||(view==='register'&&!accepted)}>{busy?<><LoaderCircle className="spin" size={18}/>Preparando seu espaço…</>:view==='register'?'Criar conta e conversar':'Entrar no REP'}</button><div className="auth-divider"><span/>ou<span/></div>{google?<a className="entry-secondary google-login" href="/api/auth/google" target="_top"><span className="google-g">G</span>Continuar com Google</a>:<><button type="button" className="entry-secondary google-login" disabled><span className="google-g">G</span>Google · em breve</button><p className="entry-auth-note">O acesso Google aguarda configuração. E-mail e senha já estão disponíveis.</p></>}<button type="button" className="entry-switch" onClick={()=>{setView(view==='register'?'login':'register');setFormError('')}}>{view==='register'?'Já tem conta? Entrar':'Primeira vez? Criar conta'}</button></form>}
 </>}
 {saveError&&<div className="entry-error" role="alert"><span>Seu progresso ainda não foi salvo.</span><button onClick={onSaveRetry}>Tentar salvar novamente</button></div>}{(error||formError)&&<div className="entry-error" role="alert"><span>{formError||error}</span>{error&&<button onClick={onRetry}>Tentar novamente</button>}</div>}
 <div className="entry-assurance"><ShieldCheck size={14}/><span>Seu perfil e progresso salvos na sua conta.</span></div>
 </motion.div></AnimatePresence><div className="entry-surface-footer"><span>BUILT AROUND YOU</span><span className="entry-legal-links"><a href="/termos" target="_top">Termos</a><a href="/privacidade" target="_top">Privacidade</a><span>REP © 2026</span></span></div></main></div></div>
}
