import React,{useState} from 'react';
import {ArrowLeft,ArrowUpRight,CheckCircle2,Database,LockKeyhole,ShieldCheck,UserCheck} from 'lucide-react';
import Logo from './brand/Logo';

const UPDATED='1 de outubro de 2026';

function LegalHeader({title,eyebrow,description}){
 return <><header className="legal-topbar"><a href="/" className="legal-brand"><Logo/><span>TYVON</span></a><a href="/" className="legal-back"><ArrowLeft size={16}/>Voltar ao TYVON</a></header><section className="legal-hero"><span className="legal-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p><small>Última atualização: {UPDATED}</small></section></>
}

function PrivacyRequest(){
 const [email,setEmail]=useState(''),[kind,setKind]=useState('access'),[details,setDetails]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 async function submit(e){
  e.preventDefault();setBusy(true);setError('');setResult(null);
  try{
   const response=await fetch('/api/privacy/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,kind,details})});
   const data=await response.json().catch(()=>({}));
   if(!response.ok)throw new Error(data.error||'Não foi possível registrar a solicitação.');
   setResult(data);setDetails('');
  }catch(err){setError(err.message)}finally{setBusy(false)}
 }
 return <section className="legal-request" id="direitos"><div className="legal-request-copy"><span className="legal-kicker">SEUS DIREITOS</span><h2>Solicitação de privacidade</h2><p>Use este canal para exercer direitos relacionados aos seus dados. O TYVON poderá confirmar sua identidade antes de concluir pedidos que envolvam acesso, correção, portabilidade ou exclusão.</p></div><form onSubmit={submit}><label>E-mail<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com"/></label><label>Tipo de solicitação<select value={kind} onChange={e=>setKind(e.target.value)}><option value="access">Acesso aos meus dados</option><option value="correction">Correção de dados</option><option value="deletion">Exclusão de dados</option><option value="portability">Portabilidade</option><option value="consent">Revogar consentimento</option><option value="sharing">Informações sobre compartilhamento</option><option value="automated">Revisão/explicação de tratamento automatizado</option><option value="other">Outro assunto de privacidade</option></select></label><label>Detalhes<textarea maxLength={4000} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Explique o pedido de forma objetiva."/></label><button disabled={busy}>{busy?'Registrando…':'Registrar solicitação'}</button>{error&&<p className="legal-form-error" role="alert">{error}</p>}{result&&<p className="legal-form-success" role="status"><CheckCircle2 size={16}/>Solicitação registrada. Protocolo: <strong>{result.protocol}</strong></p>}</form></section>
}

function Privacy(){
 return <div className="legal-shell"><LegalHeader eyebrow="PRIVACIDADE / LGPD" title="Política de Privacidade" description="Como o TYVON coleta, usa, protege e compartilha dados pessoais para operar sua conta, personalizar a experiência e oferecer recursos de treino com IA."/><main className="legal-content">
  <section className="legal-summary"><div><ShieldCheck size={19}/><strong>Privacidade por padrão</strong><span>Coletamos o necessário para operar a conta e os recursos escolhidos por você.</span></div><div><LockKeyhole size={19}/><strong>Segurança</strong><span>Sessões protegidas, senha com hash e segredos mantidos no servidor.</span></div><div><UserCheck size={19}/><strong>Controle</strong><span>Você pode editar seu perfil, excluir a conta e registrar solicitações de titular.</span></div></section>
  <article>
   <h2>1. Quem controla os dados</h2><p>O responsável pela operação do TYVON atua como controlador dos dados pessoais tratados para prestar o serviço, definir suas finalidades e atender solicitações dos titulares. Para assuntos de privacidade, utilize o canal de solicitação disponível nesta própria página.</p>
   <h2>2. Quais dados podemos tratar</h2><p>Podemos tratar dados de cadastro e autenticação, como e-mail, nome de conta, identificadores de sessão e, quando você escolher entrar com Google, identificadores necessários ao OAuth. Também tratamos os dados que você informa para personalizar o TYVON, como nome de preferência, idade, peso, objetivo, experiência, equipamentos, frequência de treino, mensagens, histórico de treinos e preferências de interface.</p><p>Se você optar por informar dor, lesão, limitação física ou outra informação relacionada à saúde, esse dado pode ser considerado dado pessoal sensível. O fornecimento é opcional e seu uso é limitado à personalização de alertas de segurança e da experiência de treino.</p>
   <h2>3. Para que usamos os dados</h2><p>Usamos dados para criar e autenticar sua conta, salvar progresso, gerar e adaptar planos, responder no chat, exibir histórico e evolução, prevenir fraude e abuso, manter a segurança do serviço, diagnosticar falhas e atender obrigações legais ou solicitações relacionadas à privacidade.</p>
   <h2>4. Bases legais</h2><p>Conforme o contexto, o tratamento pode se apoiar na execução de contrato ou de procedimentos preliminares, consentimento, cumprimento de obrigação legal ou regulatória, exercício regular de direitos e legítimo interesse, sempre observando necessidade, transparência e os demais princípios da LGPD. Informações sensíveis fornecidas voluntariamente são tratadas somente para finalidades específicas e compatíveis com a segurança e personalização do serviço.</p>
   <h2>5. Crianças e adolescentes</h2><p>O TYVON é destinado a pessoas com 14 anos ou mais. Para usuários menores de 18 anos, o tratamento considera o melhor interesse do adolescente, e o produto recomenda acompanhamento de responsável e profissional qualificado para atividades físicas. O TYVON não deve ser usado para substituir avaliação médica ou supervisão apropriada.</p>
   <h2>6. IA e decisões automatizadas</h2><p>Mensagens e partes necessárias do perfil podem ser enviadas ao provedor de IA configurado para produzir respostas. O TYVON usa esses resultados como apoio e aplica regras próprias de segurança e apresentação. A IA pode errar e não realiza diagnóstico médico. Caso um tratamento automatizado afete seus interesses, você pode pedir informações sobre os critérios utilizados e solicitar revisão quando aplicável.</p>
   <h2>7. Compartilhamento e operadores</h2><p>Dados podem ser tratados por prestadores necessários à operação, incluindo infraestrutura de hospedagem e banco de dados, autenticação opcional e processamento de IA. No ambiente atual, isso pode envolver Render, Google e NVIDIA, conforme o recurso utilizado. Esses fornecedores recebem apenas dados compatíveis com a finalidade do serviço e atuam sob seus próprios termos e controles de segurança.</p>
   <h2>8. Transferências internacionais</h2><p>Alguns fornecedores podem processar dados fora do Brasil. Quando houver transferência internacional de dados pessoais, o TYVON busca adotar mecanismos compatíveis com a LGPD e com a regulamentação da ANPD aplicável às transferências internacionais.</p>
   <h2>9. Retenção e exclusão</h2><p>Os dados são mantidos pelo tempo necessário para prestar o serviço, cumprir obrigações legais, prevenir fraude, resolver disputas e exercer direitos. Você pode excluir o perfil/conta pelos controles disponíveis no produto. Alguns registros estritamente necessários podem ser mantidos pelo prazo exigido por lei ou para demonstração de cumprimento de obrigações.</p>
   <h2>10. Segurança e incidentes</h2><p>Adotamos medidas técnicas e administrativas compatíveis com os riscos do serviço, incluindo proteção de credenciais, cookies de sessão protegidos, limitação de tentativas de acesso e segregação de segredos no servidor. Nenhum sistema é imune a incidentes; quando um incidente puder gerar risco ou dano relevante, serão adotadas as providências de avaliação e comunicação exigidas pela legislação e pela regulamentação da ANPD.</p>
   <h2>11. Seus direitos</h2><p>Nos termos da LGPD, você pode solicitar, conforme aplicável, confirmação de tratamento, acesso, correção, anonimização, bloqueio ou eliminação de dados inadequados, portabilidade, informação sobre compartilhamentos, informação sobre consentimento, revogação do consentimento, oposição, revisão ou explicação de decisões automatizadas e outros direitos previstos em lei. O exercício é gratuito, sujeito à validação de identidade e às hipóteses legais de retenção.</p>
   <h2>12. Cookies e armazenamento local</h2><p>O TYVON usa cookies técnicos de sessão para autenticação e pode usar armazenamento local do navegador para preservar estado necessário à experiência e migração de perfis. Não descrevemos cookies publicitários porque eles não fazem parte do funcionamento atual do produto.</p>
   <h2>13. Atualizações desta política</h2><p>Esta política pode ser atualizada quando o produto, os fornecedores ou as regras aplicáveis mudarem. Alterações relevantes serão apresentadas de forma adequada no serviço, com indicação da data de atualização.</p>
   <div className="legal-official"><Database size={18}/><div><strong>Referências oficiais</strong><p>LGPD (Lei nº 13.709/2018), regulamentações e orientações da Autoridade Nacional de Proteção de Dados.</p><a href="https://www.gov.br/anpd/pt-br/assuntos/titular-de-dados-1/direito-dos-titulares" target="_blank" rel="noreferrer">Direitos dos titulares · ANPD <ArrowUpRight size={14}/></a></div></div>
  </article><PrivacyRequest/></main><LegalFooter/></div>
}

function Terms(){
 return <div className="legal-shell"><LegalHeader eyebrow="TYVON / REGRAS DE USO" title="Termos de Uso" description="As regras para criar uma conta, usar os recursos do TYVON e entender os limites do chat e dos planos de treino."/><main className="legal-content"><article>
  <h2>1. Aceitação</h2><p>Ao criar uma conta ou utilizar o TYVON, você concorda com estes Termos e com a Política de Privacidade. Se não concordar, não utilize o serviço.</p>
  <h2>2. O que é o TYVON</h2><p>O TYVON é um serviço digital de organização de treinos, registro de progresso e apoio conversacional com recursos de inteligência artificial. Ele oferece orientações gerais e ferramentas de planejamento, mas não substitui avaliação de médico, fisioterapeuta, nutricionista, profissional de educação física ou outro profissional habilitado.</p>
  <h2>3. Idade e supervisão</h2><p>É necessário ter 14 anos ou mais para criar uma conta. Usuários menores de 18 anos devem utilizar orientações de treino com participação de responsável e acompanhamento profissional adequado, especialmente para escolha de cargas, execução técnica, retorno após lesão ou qualquer situação de saúde.</p>
  <h2>4. Conta e segurança</h2><p>Você é responsável por fornecer informações verdadeiras, manter sua senha em sigilo e avisar caso perceba uso não autorizado. Não compartilhe credenciais nem tente acessar contas de terceiros.</p>
  <h2>5. Limitações da IA e do conteúdo</h2><p>Respostas geradas por IA podem conter erros, omissões ou interpretações inadequadas. Não trate uma resposta do TYVON como diagnóstico, prescrição, garantia de resultado ou ordem profissional. Em caso de dor, mal-estar, lesão ou dúvida sobre segurança, interrompa a atividade e procure orientação qualificada.</p>
  <h2>6. Uso permitido</h2><p>Você pode usar o TYVON para fins pessoais e legítimos relacionados à organização de treino e acompanhamento da própria rotina. Não é permitido explorar falhas, interferir na segurança, automatizar abusivamente requisições, distribuir malware, tentar obter dados de terceiros ou usar o serviço de forma ilegal.</p>
  <h2>7. Conteúdo e dados enviados por você</h2><p>Você continua responsável pelas informações que fornece. Ao inserir dados necessários ao funcionamento do TYVON, você autoriza o tratamento na medida descrita na Política de Privacidade. Evite inserir dados de terceiros ou informações desnecessárias.</p>
  <h2>8. Propriedade intelectual</h2><p>A marca TYVON, identidade visual, interface, textos próprios, componentes autorais e demais elementos do produto são protegidos conforme a legislação aplicável, sem prejuízo das licenças de bibliotecas e componentes de terceiros identificadas no projeto.</p>
  <h2>9. Disponibilidade e mudanças</h2><p>O serviço pode passar por manutenção, atualização ou indisponibilidade temporária. Recursos podem evoluir para melhorar segurança, desempenho ou adequação legal. Alterações materiais nestes Termos serão comunicadas de forma apropriada.</p>
  <h2>10. Suspensão e encerramento</h2><p>Contas ou acessos podem ser limitados em caso de fraude, abuso, risco de segurança ou violação destes Termos, respeitada a legislação aplicável. Você pode encerrar sua conta pelos recursos disponíveis no produto.</p>
  <h2>11. Responsabilidade</h2><p>O TYVON busca fornecer uma experiência segura e útil, mas resultados físicos dependem de fatores individuais e não são garantidos. O usuário deve respeitar seus limites, utilizar técnica adequada e procurar acompanhamento profissional quando necessário.</p>
  <h2>12. Privacidade</h2><p>O tratamento de dados pessoais segue a <a href="/privacidade">Política de Privacidade</a>, que explica dados tratados, finalidades, fornecedores, segurança, retenção e direitos previstos na LGPD.</p>
  <h2>13. Lei aplicável</h2><p>Estes Termos são regidos pela legislação brasileira, incluindo a LGPD, o Marco Civil da Internet e normas de proteção do consumidor quando aplicáveis. Eventuais controvérsias serão tratadas pelo foro competente nos termos da legislação.</p>
 </article></main><LegalFooter/></div>
}

function LegalFooter(){return <footer className="legal-footer"><Logo small/><span>TYVON © 2026</span><nav><a href="/termos">Termos de Uso</a><a href="/privacidade">Política de Privacidade</a></nav></footer>}

export default function LegalPage({type}){return type==='terms'?<Terms/>:<Privacy/>}
