import React,{useRef} from 'react';
import {Check,Send,Dumbbell} from 'lucide-react';
import Logo from './brand/Logo';
export const appStyles=[{id:'essential',name:'Essencial',description:'Preto e branco. Foco no seu ritmo.'},{id:'energy',name:'Energia',description:'Ameixa e âmbar. Um toque de energia.'}];
export default function ThemePicker({value='essential',onChange,disabled=false}){
 const buttons=useRef([]),style=appStyles.find(s=>s.id===value)||appStyles[0];
 function keyboard(e,index){let next;if(e.key==='ArrowRight'||e.key==='ArrowDown')next=(index+1)%appStyles.length;if(e.key==='ArrowLeft'||e.key==='ArrowUp')next=(index-1+appStyles.length)%appStyles.length;if(e.key==='Home')next=0;if(e.key==='End')next=appStyles.length-1;if(next!==undefined){e.preventDefault();onChange(appStyles[next].id);buttons.current[next]?.focus()}}
 return <div className="appearance-preview-picker"><div className="style-picker style-switcher" role="radiogroup" aria-label="Escolha o estilo do app">{appStyles.map((s,index)=><button type="button" role="radio" aria-label={`Estilo ${s.name}`} aria-checked={value===s.id} tabIndex={value===s.id?0:-1} disabled={disabled} key={s.id} ref={node=>buttons.current[index]=node} className={'style-option '+(value===s.id?'is-selected':'')} onClick={()=>onChange(s.id)} onKeyDown={e=>keyboard(e,index)}><span>{s.name}</span><span className="style-selected-icon" aria-hidden="true">{value===s.id&&<Check size={15}/>}</span></button>)}</div><div className="style-preview style-preview-large" data-style={style.id} aria-label={`Prévia do estilo ${style.name}`}><div className="style-preview-header"><Logo/><span>PRÉVIA · REP AI</span></div><div className="style-preview-conversation" aria-hidden="true"><div className="style-preview-bot"><img src="/brand/rep-bot-poster.png" alt=""/><span>Vamos no seu ritmo.</span></div><div className="style-preview-user">Vamos!</div></div><div className="style-preview-workout style-preview-workout-wide" aria-hidden="true"><Dumbbell size={23}/><div><strong>Seu próximo treino</strong><span>Exercícios feitos para você</span></div><div className="style-preview-start">Começar</div></div><div className="style-preview-input" aria-hidden="true"><span>Converse com o REP…</span><Send size={17}/></div></div><p className="style-preview-description">{style.description}</p></div>
}
