import React,{useMemo,useState} from 'react';
import {ArrowUpRight,BarChart3,Check,Clock,Dumbbell,Share2,TrendingUp} from 'lucide-react';
export default function V2Analytics({p,logs}){
 const [shareState,setShareState]=useState('');const v2=logs.filter(l=>l.engine==='v2'),latest=v2.at(-1);
 const stats=useMemo(()=>{const sets=v2.flatMap(l=>l.setLogs||[]),reps=sets.reduce((a,s)=>a+(Number(s.reps)||0),0),volume=sets.reduce((a,s)=>a+(Number(s.weight)||0)*(Number(s.reps)||0),0),minutes=v2.reduce((a,l)=>a+(Number(l.minutes)||0),0);return {sets,reps,volume,minutes}},[v2]);
 const byExercise=useMemo(()=>{const map={};for(const s of stats.sets){if(!map[s.exerciseName])map[s.exerciseName]={max:0,reps:0};map[s.exerciseName].max=Math.max(map[s.exerciseName].max,Number(s.weight)||0);map[s.exerciseName].reps+=Number(s.reps)||0}return Object.entries(map).sort((a,b)=>b[1].max-a[1].max)},[stats]);
 async function share(){if(!latest||p.age<18)return;setShareState('sharing');try{const r=await fetch('/api/v2/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workoutName:latest.name,sets:latest.sets,minutes:latest.minutes})});const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível compartilhar.');setShareState('shared')}catch(e){setShareState(e.message)}}
 return <div className="v2-page"><header className="v2-title"><span className="v2-pill"><TrendingUp size={14}/>PROGRESS ENGINE</span><h1>O que suas séries estão dizendo.</h1><p>A V2 usa performance registrada, não estimativas genéricas, para orientar a próxima sessão.</p></header>
 <div className="v2-stat-grid"><div><Dumbbell/><span>Séries registradas</span><strong>{stats.sets.length}</strong></div><div><BarChart3/><span>Repetições</span><strong>{stats.reps}</strong></div><div><TrendingUp/><span>Volume registrado</span><strong>{Math.round(stats.volume).toLocaleString('pt-BR')} kg</strong></div><div><Clock/><span>Tempo V2</span><strong>{stats.minutes} min</strong></div></div>
 <div className="v2-analytics-grid"><section className="v2-progress-list"><div className="v2-section-head"><div><span>EXERCÍCIOS</span><h2>Melhores referências registradas</h2></div><TrendingUp size={23}/></div>{byExercise.length?byExercise.slice(0,8).map(([name,s])=><div key={name}><span>{name}</span><strong>{s.max?s.max+' kg':s.reps+' reps'}</strong></div>):<p className="v2-empty">Conclua um treino V2 registrando reps e RIR para começar a construir seu histórico.</p>}</section>
 <section className="v2-share-card"><Share2 size={28}/><span>TYVON CIRCLE</span><h2>Compartilhe a sessão, não o corpo.</h2><p>O Circle publica apenas nome do treino, séries e duração. Sem foto corporal, peso ou comentários.</p>{p.age<18?<small>Compartilhamento público fica desativado para menores de 18 anos nesta versão.</small>:<button disabled={!latest||shareState==='sharing'||shareState==='shared'} onClick={share}>{shareState==='shared'?<><Check size={16}/>Compartilhado</>:shareState==='sharing'?'Compartilhando…':<><Share2 size={16}/>Compartilhar último treino</>}</button>}{shareState&&!['sharing','shared'].includes(shareState)&&<small>{shareState}</small>}</section></div>
 {latest&&<section className="v2-last-session"><div><span>ÚLTIMA SESSÃO</span><h2>{latest.name}</h2><p>{new Date(latest.date).toLocaleDateString('pt-BR')} · {latest.minutes} min · esforço {latest.feedback?.effort||'—'}/5</p></div><ArrowUpRight size={24}/></section>}
 </div>
}
