import React,{useEffect,useMemo,useState} from 'react';
import {Activity,ArrowRight,BarChart3,Clock,Dumbbell,MessageSquare,Sparkles,Users} from 'lucide-react';
import Bot from './Bot';
import {weeklyVolumeV2} from '../shared/workouts-v2.js';
export default function V2Home({p,plan,logs,go,start,ask,nextWorkoutId=0}){
 const [feed,setFeed]=useState([]);useEffect(()=>{fetch('/api/v2/social').then(r=>r.ok?r.json():{items:[]}).then(d=>setFeed(d.items||[])).catch(()=>{})},[]);
 const volume=useMemo(()=>weeklyVolumeV2(plan),[plan]),latest=logs.at(-1),w=plan[Math.min(nextWorkoutId,plan.length-1)],setCount=(latest?.setLogs||[]).length;
 const insight=latest?.engine==='v2'?'A última sessão registrou '+setCount+' séries detalhadas. A próxima ficha já usa essas reps e RIR como referência.':'Faça o primeiro treino V2 registrando reps e RIR para desbloquear progressão adaptativa.';
 return <div className="v2-page"><header className="v2-hero"><div><span className="v2-pill"><Sparkles size={14}/>TYVON V2 · EXPERIMENTAL</span><h1>Treino que aprende<br/>com o que você faz.</h1><p>Programa estável, registro por série e progressão explicável.</p></div><Bot/></header>
 <section className="v2-intelligence"><div><span>ADAPTIVE ENGINE</span><h2>{insight}</h2><button onClick={()=>go('chat')}><MessageSquare size={17}/>Conversar com TYVON</button></div><div className="v2-mini-metrics"><span><strong>{logs.filter(x=>x.engine==='v2').length}</strong>sessões V2</span><span><strong>{Object.values(volume).reduce((a,b)=>a+b,0)}</strong>séries/semana planejadas</span><span><strong>{p.sessionMinutes||50}</strong>min por sessão</span></div></section>
 <div className="v2-grid"><section className="v2-next"><div className="v2-section-head"><div><span>PRÓXIMA SESSÃO</span><h2>{w.name}</h2><p>{w.focus}</p></div><Dumbbell size={25}/></div><div className="v2-exercise-list">{w.exercises.slice(0,4).map(e=><div key={e.id||e.name}><div><strong>{e.name}</strong><span>{e.sets} × {e.reps} · RIR {e.targetRir}</span></div><small>{e.suggestedLoad!=null?'ref. '+e.suggestedLoad+' kg':'nova referência'}</small></div>)}</div><button className="v2-primary" onClick={()=>start(w)}>Começar treino<ArrowRight size={17}/></button></section>
 <section className="v2-volume"><div className="v2-section-head"><div><span>VOLUME SEMANAL</span><h2>Distribuição atual</h2></div><BarChart3 size={24}/></div><div>{Object.entries(volume).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([group,value])=><div className="v2-volume-row" key={group}><span>{group}</span><i><b style={{width:Math.min(100,value/14*100)+'%'}}/></i><strong>{value}</strong></div>)}</div><button className="v2-link" onClick={()=>go('workouts')}>Abrir plano completo</button></section></div>
 <section className="v2-quick"><button onClick={()=>ask('Qual treino faço hoje?')}><Activity size={19}/><span><strong>Meu treino hoje</strong><small>Usar sequência e histórico</small></span></button><button onClick={()=>go('analytics')}><BarChart3 size={19}/><span><strong>Minha progressão</strong><small>Reps, RIR e volume</small></span></button><button onClick={()=>go('profile')}><Clock size={19}/><span><strong>Ajustar duração</strong><small>{p.sessionMinutes||50} min por sessão</small></span></button></section>
 <section className="v2-circle"><div className="v2-section-head"><div><span>TYVON CIRCLE</span><h2>Treinos compartilhados</h2><p>Somente resumos estruturados. Sem comentários ou comparação corporal.</p></div><Users size={24}/></div>{feed.length?<div className="v2-feed">{feed.slice(0,6).map(item=><div key={item.id}><span className="v2-feed-avatar">{item.displayName.slice(0,2).toUpperCase()}</span><div><strong>{item.displayName} concluiu {item.workoutName}</strong><small>{item.sets} séries · {item.minutes} min</small></div></div>)}</div>:<p className="v2-empty">O Circle ainda está vazio. Usuários adultos podem compartilhar um resumo pela tela de evolução.</p>}</section>
 </div>
}
