import React,{useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {Check,ChevronLeft,ChevronRight,Clock,Pause,Play,Sparkles,X,Zap} from 'lucide-react';
import Logo from './brand/Logo';
const targetMid=reps=>{const m=String(reps).match(/(\d+)\D+(\d+)/);return m?Math.round((Number(m[1])+Number(m[2]))/2):10};
export default function V2WorkoutSession({workout:w,finish,close,restricted,profile}){
 const [index,setIndex]=useState(0),[sets,setSets]=useState({}),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(true),[rest,setRest]=useState(0),[confirmClose,setConfirmClose]=useState(false),[summary,setSummary]=useState(false),[effort,setEffort]=useState(3),reduced=useReducedMotion();
 const e=w.exercises[index],total=useMemo(()=>w.exercises.reduce((a,x)=>a+x.sets,0),[w]),done=Object.values(sets).filter(s=>s.completed).length,percent=Math.round(done/Math.max(1,total)*100);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>{setSeconds(v=>v+1);setRest(v=>Math.max(0,v-1))},1000);return()=>clearInterval(id)},[running]);
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
 const format=t=>Math.floor(t/60).toString().padStart(2,'0')+':'+(t%60).toString().padStart(2,'0'),key=i=>index+'-'+i;
 function patch(i,data){setSets(v=>({...v,[key(i)]:{weight:'',reps:'',rir:e.targetRir??2,completed:false,...v[key(i)],...data}}))}
 function complete(i){const current={weight:e.suggestedLoad??'',reps:'',rir:e.targetRir??2,completed:false,...sets[key(i)]};if(!current.completed&&(!current.reps||Number(current.reps)<=0))return;patch(i,{completed:!current.completed});if(!current.completed){setRest(e.restSeconds||90);navigator.vibrate?.(25)}}
 function payload(){const setLogs=[];w.exercises.forEach((ex,exIndex)=>{for(let i=0;i<ex.sets;i++){const s=sets[exIndex+'-'+i]||{};if(s.completed)setLogs.push({exerciseId:ex.id||'',exerciseName:ex.name,group:ex.group,setIndex:i+1,weight:Number(s.weight)||0,reps:Number(s.reps)||0,rir:Number(s.rir),completed:true,targetRir:ex.targetRir??null})}});return {name:w.name,minutes:Math.max(1,Math.round(seconds/60)),sets:setLogs.length,setLogs,feedback:{effort},engine:'v2'}}
 return <motion.div className="workout-session v2-session" role="dialog" aria-modal="true" aria-label={'Treino V2 '+w.name} initial={{opacity:0,y:'100%'}} animate={{opacity:1,y:0}} exit={{opacity:0,y:'100%'}} transition={{duration:reduced?0:.4,ease:[.22,1,.36,1]}}>
 <header className="session-appbar"><button aria-label="Encerrar treino" onClick={()=>setConfirmClose(true)}><X size={23}/></button><Logo/><div className="v2-live"><Sparkles size={14}/>V2 ADAPTIVE</div></header>
 {confirmClose?<div className="session-confirm"><div><span className="session-kicker">TREINO PAUSADO</span><h2>Parar por aqui?</h2><p>Você registrou {done} de {total} séries. A V2 aprende somente com as séries salvas.</p><div className="session-confirm-actions"><button className="session-main-action" onClick={()=>setConfirmClose(false)}>Continuar treino</button>{done>0&&<button onClick={()=>finish(payload())}>Salvar parcial</button>}<button onClick={close}>Sair sem salvar</button></div></div></div>:summary?<motion.div className="session-finish v2-finish" initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}}><span className="finish-icon"><Check size={34}/></span><span className="session-kicker">DADOS SALVOS PARA PROGRESSÃO</span><h2>Treino concluído.</h2><p>{done} séries em {format(seconds)}. Carga, reps e RIR vão alimentar a próxima recomendação da V2.</p><div className="v2-feedback"><span>Como ficou a sessão?</span><div>{[1,2,3,4,5].map(n=><button key={n} className={effort===n?'active':''} onClick={()=>setEffort(n)} aria-label={'Esforço '+n+' de 5'}>{n}</button>)}</div><small>1 = muito leve · 5 = muito exigente</small></div><button className="session-main-action" onClick={()=>finish(payload())}>Salvar e ver evolução</button></motion.div>:<>
 <div className="session-progress-head"><div><span className="session-kicker">REP V2 · {String(index+1).padStart(2,'0')} DE {String(w.exercises.length).padStart(2,'0')}</span><strong>{percent}% concluído</strong></div><div className="session-timer"><Clock size={17}/><strong>{format(seconds)}</strong><button aria-label={running?'Pausar':'Retomar'} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>}</button></div></div>
 <div className="session-progress-line"><motion.i animate={{width:percent+'%'}}/></div>
 <main className="session-body"><AnimatePresence mode="wait"><motion.section className="session-focus" key={index} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}><div className="session-muscle"><span>{e.group}</span><small>{e.equipment}</small></div><h1>{e.name}</h1><p>{e.tip}</p>{restricted&&<div className="session-warning">Você informou uma restrição. Valide o exercício com um profissional.</div>}<div className="v2-adaptive-card"><Sparkles size={17}/><div><strong>{profile?.age<18?'Progressão supervisionada':e.suggestedLoad!=null?'Referência: '+e.suggestedLoad+' kg':'Criando sua referência'}</strong><span>{profile?.age<18?'A V2 não aumenta carga automaticamente para menores de 18 anos.':e.progressionReason}</span></div></div><div className="session-prescription"><span><strong>{e.sets}</strong>séries</span><span><strong>{e.reps}</strong>reps</span><span><strong>RIR {e.targetRir}</strong>alvo</span><span><strong>{e.restSeconds}s</strong>descanso</span></div></motion.section></AnimatePresence>
 <section className="session-sets"><div className="session-sets-title"><div><span className="session-kicker">SÉRIES PRINCIPAIS</span><h2>Registre o que aconteceu</h2></div>{e.warmupSets>0&&<span className="warmup-pill"><Zap size={14}/>{e.warmupSets} aquecimento</span>}</div>{Array.from({length:e.sets},(_,i)=>{const s={weight:e.suggestedLoad??'',reps:'',rir:e.targetRir??2,completed:false,...sets[key(i)]};return <motion.div layout key={i} className={'session-set v2-set '+(s.completed?'is-complete':'')}><span className="set-number">{String(i+1).padStart(2,'0')}</span><label><small>CARGA</small><span><input inputMode="decimal" type="number" min="0" max="500" step="0.5" placeholder={e.equipment==='Peso corporal'?'0':String(e.suggestedLoad??0)} value={s.weight} onChange={ev=>patch(i,{weight:ev.target.value})}/> kg</span></label><label><small>REPS</small><input inputMode="numeric" type="number" min="1" max="100" placeholder={String(targetMid(e.reps))} value={s.reps} onChange={ev=>patch(i,{reps:ev.target.value})}/></label><label><small>RIR</small><select value={s.rir} onChange={ev=>patch(i,{rir:Number(ev.target.value)})}>{[0,1,2,3,4,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label><button aria-label={'Concluir série '+(i+1)} aria-pressed={s.completed} onClick={()=>complete(i)}>{s.completed?<Check size={22}/>:<span/>}</button></motion.div>})}</section>
 <AnimatePresence>{rest>0&&<motion.section className="session-rest" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:18}}><div className="rest-ring" style={{'--rest-progress':Math.max(0,rest/(e.restSeconds||90))*360+'deg'}}><span>{format(rest)}</span></div><div><span className="session-kicker">RECUPERE</span><h3>A próxima série vale pela qualidade.</h3></div><button onClick={()=>setRest(0)}>Pular</button></motion.section>}</AnimatePresence>
 </main><footer className="session-footer"><button className="session-prev" disabled={index===0} onClick={()=>{setIndex(index-1);setRest(0)}}><ChevronLeft size={20}/>Anterior</button>{index<w.exercises.length-1?<button className="session-next" onClick={()=>{setIndex(index+1);setRest(0)}}>Próximo exercício<ChevronRight size={20}/></button>:<button className="session-next" disabled={!done} onClick={()=>{setRunning(false);setSummary(true)}}>Finalizar treino<Check size={20}/></button>}</footer></>}
 </motion.div>
}
