import React,{useMemo,useState} from 'react';
import {Activity,Clock,Dumbbell,Play,Sparkles,Target} from 'lucide-react';
import {weeklyVolumeV2} from '../shared/workouts-v2.js';
export default function V2Workouts({p,plan,start}){
 const [selected,setSelected]=useState(0),w=plan[Math.min(selected,plan.length-1)],volume=useMemo(()=>weeklyVolumeV2(plan),[plan]);
 return <div className="v2-page"><header className="v2-title"><span className="v2-pill"><Sparkles size={14}/>TRAINING ENGINE V2</span><h1>Seu programa adaptativo.</h1><p>{p.days} dias · {p.sessionMinutes||50} min · exercícios preservados para a progressão fazer sentido.</p></header>
 <div className="v2-workout-layout"><aside><div className="v2-session-tabs">{plan.map((item,i)=><button className={selected===i?'active':''} key={item.id} onClick={()=>setSelected(i)}><span>{String.fromCharCode(65+i)}</span><div><strong>{item.name}</strong><small>{item.exercises.length} exercícios · {item.minutes} min</small></div></button>)}</div><div className="v2-volume-summary"><span>VOLUME DIRETO / SEMANA</span>{Object.entries(volume).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([g,v])=><div key={g}><span>{g}</span><strong>{v} séries</strong></div>)}</div></aside>
 <section className="v2-plan-card"><div className="v2-plan-head"><div><span>{w.method}</span><h2>{w.name}</h2><p>{w.focus}</p></div><button className="v2-primary" onClick={()=>start(w)}><Play size={16} fill="currentColor"/>Começar</button></div><div className="v2-plan-meta"><span><Clock size={15}/>{w.minutes} min</span><span><Target size={15}/>{w.intensity}</span><span><Activity size={15}/>histórico ativo</span></div><div className="v2-plan-exercises">{w.exercises.map((e,i)=><article key={e.id||e.name}><span className="v2-index">{String(i+1).padStart(2,'0')}</span><div className="v2-ex-copy"><strong>{e.name}</strong><small>{e.group} · {e.equipment}</small><p>{e.progressionReason}</p></div><div className="v2-prescription"><strong>{e.sets} × {e.reps}</strong><span>RIR {e.targetRir} · {e.restSeconds}s</span>{e.suggestedLoad!=null&&p.age>=18?<b>{e.suggestedLoad} kg ref.</b>:null}</div></article>)}</div><div className="v2-plan-note"><Dumbbell size={17}/><span>{w.progression}</span></div></section></div></div>
}
