import React,{useEffect,useState} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import {ArrowRight,Check,Clock,Dumbbell,Play,Sparkles,X} from 'lucide-react';
import Logo from './brand/Logo';

export default function WorkoutReveal({profile,plan,onStart,onClose}){
 const [selected,setSelected]=useState(0),[entered,setEntered]=useState(false),reduced=useReducedMotion(),w=plan[selected];
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
 const letter=String.fromCharCode(65+w.id),strength=plan.filter(x=>x.kind==='strength').length;
 return <motion.div className="workout-reveal" role="dialog" aria-modal="true" aria-label="Seu plano REP está pronto" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduced?0:.35}}>
  <motion.div className="reveal-ambient" aria-hidden="true" animate={reduced?{}:{rotate:[0,4,-3,0],scale:[1,1.05,1]}} transition={{duration:12,repeat:Infinity,ease:'easeInOut'}}/>
  <header className="reveal-header"><Logo/><button aria-label="Ir para o início" onClick={onClose}><X size={22}/></button></header>
  <AnimatePresence mode="wait">
   {!entered?<motion.section className="reveal-intro" key="intro" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-18}} transition={{duration:reduced?0:.45,ease:[.22,1,.36,1]}}><span className="reveal-kicker"><Sparkles size={15}/>SEU PLANO ESTÁ PRONTO</span><h1>Feito para o seu<br/><span>ritmo, {profile.name.split(' ')[0]}.</span></h1><p>{strength} sessões de força · {profile.days} dias por semana · {profile.experience}</p><div className="reveal-orbit" aria-hidden="true"><span>REP</span><i/><i/><i/></div><button className="reveal-enter" onClick={()=>setEntered(true)}>Conhecer meu plano<ArrowRight size={19}/></button></motion.section>
   :<motion.section className="reveal-plan" key="plan" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:reduced?0:.4,ease:[.22,1,.36,1]}}><div className="reveal-title"><span className="reveal-kicker">ESCOLHA SEU TREINO</span><h1>Por onde você<br/>quer começar?</h1></div><div className="reveal-tabs" role="tablist" aria-label="Treinos do seu plano">{plan.map((item,i)=><button key={item.id} role="tab" aria-selected={selected===i} onClick={()=>setSelected(i)}><span>{item.kind==='recovery'?'R':String.fromCharCode(65+item.id)}</span><small>{i===0?'RECOMENDADO':item.kind==='recovery'?'RECUPERAÇÃO':`TREINO ${String.fromCharCode(65+item.id)}`}</small></button>)}</div><AnimatePresence mode="wait"><motion.article className="reveal-workout-card" key={w.id} initial={{opacity:0,x:24,scale:.98}} animate={{opacity:1,x:0,scale:1}} exit={{opacity:0,x:-24,scale:.98}} transition={{duration:reduced?0:.3,ease:[.22,1,.36,1]}}><div className="reveal-card-index" aria-hidden="true">{letter}</div><div className="reveal-card-top"><span>{w.kind==='recovery'?'RECUPERAÇÃO ATIVA':w.method}</span><span>{selected+1} / {plan.length}</span></div><h2>{w.name}</h2><p>{w.focus}</p><div className="reveal-card-metrics"><span><Clock size={17}/><strong>{w.minutes}</strong> min</span><span><Dumbbell size={17}/><strong>{w.exercises.length}</strong> exercícios</span></div><div className="reveal-exercises">{w.exercises.slice(0,3).map((e,i)=><div key={e.name}><span>{String(i+1).padStart(2,'0')}</span><strong>{e.name}</strong><small>{e.sets} × {e.reps}</small></div>)}</div><div className="reveal-ready"><Check size={16}/><span>{w.intensity}</span></div></motion.article></AnimatePresence><button className="reveal-start" onClick={()=>onStart(w)}><span><Play size={19} fill="currentColor"/>Começar treino {letter}</span><small>{w.minutes} min · toque para iniciar</small></button><button className="reveal-later" onClick={onClose}>Ver meu espaço primeiro</button></motion.section>}
  </AnimatePresence>
 </motion.div>
}
