import React,{useEffect,useMemo,useState} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'motion/react';
import {ArrowLeft,Check,ChevronLeft,ChevronRight,Clock,Pause,Play,Sparkles,X,Zap} from 'lucide-react';
import Logo from './brand/Logo';

export default function WorkoutSession({workout:w,finish,close,restricted}){
 const [index,setIndex]=useState(0),[checked,setChecked]=useState({}),[weights,setWeights]=useState({}),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(true),[rest,setRest]=useState(0),[confirmClose,setConfirmClose]=useState(false),[summary,setSummary]=useState(false),reduced=useReducedMotion();
 const e=w.exercises[index],total=useMemo(()=>w.exercises.reduce((a,x)=>a+x.sets,0),[w]),done=Object.values(checked).filter(Boolean).length,exerciseDone=Array.from({length:e.sets},(_,i)=>checked[index+'-'+i]).filter(Boolean).length,percent=Math.round(done/total*100);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>{setSeconds(v=>v+1);setRest(v=>Math.max(0,v-1))},1000);return()=>clearInterval(id)},[running]);
 useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
 const format=t=>`${Math.floor(t/60).toString().padStart(2,'0')}:${(t%60).toString().padStart(2,'0')}`;
 function toggle(i){const key=index+'-'+i,next=!checked[key];setChecked(v=>({...v,[key]:next}));if(next){setRest(e.restSeconds||90);if(navigator.vibrate)navigator.vibrate(25)}}
 function change(next){setIndex(next);setRest(0);window.scrollTo(0,0)}
 return <motion.div className="workout-session" role="dialog" aria-modal="true" aria-label={`Treino ${w.name} em andamento`} initial={{opacity:0,y:'100%'}} animate={{opacity:1,y:0}} exit={{opacity:0,y:'100%'}} transition={{duration:reduced?0:.45,ease:[.22,1,.36,1]}}>
  <header className="session-appbar"><button aria-label="Encerrar treino" onClick={()=>setConfirmClose(true)}><X size={23}/></button><Logo/><div className="session-live"><i/>AO VIVO</div></header>
  {confirmClose?<div className="session-confirm"><div><span className="session-kicker">TREINO PAUSADO</span><h2>Quer parar por aqui?</h2><p>Você concluiu {done} de {total} séries. Pode continuar ou salvar o que já fez.</p><div className="session-confirm-actions"><button className="session-main-action" onClick={()=>setConfirmClose(false)}>Continuar treino</button>{done>0&&<button onClick={()=>finish({name:w.name,minutes:Math.max(1,Math.round(seconds/60)),sets:done,weights})}>Salvar treino parcial</button>}<button onClick={close}>Sair sem salvar</button></div></div></div>:summary?<motion.div className="session-finish" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}}><div className="finish-burst" aria-hidden="true"><i/><i/><i/><i/><i/></div><span className="finish-icon"><Check size={34}/></span><span className="session-kicker">TREINO CONCLUÍDO</span><h2>Você apareceu.<br/><span>Isso conta.</span></h2><p>{done} séries em {format(seconds)}. Seu progresso já pode virar parte da sua jornada.</p><div className="finish-stats"><span><strong>{done}</strong>séries</span><span><strong>{format(seconds)}</strong>tempo</span><span><strong>{w.exercises.length}</strong>exercícios</span></div><button className="session-main-action" onClick={()=>finish({name:w.name,minutes:Math.max(1,Math.round(seconds/60)),sets:done,weights})}>Salvar e ver minha evolução</button></motion.div>:<>
   <div className="session-progress-head"><div><span className="session-kicker">{String(index+1).padStart(2,'0')} DE {String(w.exercises.length).padStart(2,'0')}</span><strong>{percent}% concluído</strong></div><div className="session-timer"><Clock size={17}/><strong>{format(seconds)}</strong><button aria-label={running?'Pausar cronômetro':'Retomar cronômetro'} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>}</button></div></div>
   <div className="session-progress-line"><motion.i animate={{width:percent+'%'}} transition={{duration:.35,ease:[.22,1,.36,1]}}/></div>
   <main className="session-body"><AnimatePresence mode="wait"><motion.section className="session-focus" key={index} initial={{opacity:0,x:24}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-24}} transition={{duration:reduced?0:.25}}><div className="session-muscle"><span>{e.group}</span><small>{e.equipment}</small></div><h1>{e.name}</h1><p>{e.tip}</p>{restricted&&<div className="session-warning">Você informou uma restrição. Valide este exercício com um profissional.</div>}<div className="session-prescription"><span><strong>{e.sets}</strong>séries</span><span><strong>{e.reps}</strong>reps</span><span><strong>{e.restSeconds}s</strong>descanso</span></div></motion.section></AnimatePresence>
    <section className="session-sets"><div className="session-sets-title"><div><span className="session-kicker">SÉRIES PRINCIPAIS</span><h2>{exerciseDone}/{e.sets} concluídas</h2></div>{e.warmupSets>0&&<span className="warmup-pill"><Zap size={14}/>{e.warmupSets} aquecimento</span>}</div>{Array.from({length:e.sets},(_,i)=>{const key=index+'-'+i,complete=!!checked[key];return <motion.div layout key={i} className={'session-set '+(complete?'is-complete':'')}><span className="set-number">{String(i+1).padStart(2,'0')}</span><label><small>CARGA</small><span><input aria-label={`Carga série ${i+1}`} inputMode="decimal" type="number" min="0" max="500" step="0.5" placeholder="0" value={weights[key]??''} onChange={ev=>setWeights(v=>({...v,[key]:ev.target.value}))}/> kg</span></label><div><small>ALVO</small><strong>{e.reps}</strong></div><button aria-label={`Concluir série ${i+1}`} aria-pressed={complete} onClick={()=>toggle(i)}>{complete?<Check size={22}/>:<span/>}</button></motion.div>})}</section>
    <AnimatePresence>{rest>0&&<motion.section className="session-rest" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:18}}><div className="rest-ring" style={{'--rest-progress':`${Math.max(0,rest/(e.restSeconds||90))*360}deg`}}><span>{format(rest)}</span></div><div><span className="session-kicker">RECUPERE</span><h3>Respire. A próxima vem forte.</h3></div><button onClick={()=>setRest(0)}>Pular</button></motion.section>}</AnimatePresence>
   </main>
   <footer className="session-footer"><button className="session-prev" disabled={index===0} onClick={()=>change(index-1)}><ChevronLeft size={20}/><span>Anterior</span></button>{index<w.exercises.length-1?<button className="session-next" onClick={()=>change(index+1)}><span>Próximo exercício</span><ChevronRight size={20}/></button>:<button className="session-next" disabled={!done} onClick={()=>{setRunning(false);setSummary(true)}}><span>Finalizar treino</span><Check size={20}/></button>}</footer>
  </>}
 </motion.div>
}
